repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# Python hooks
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        files: "backend/.*\\.py$"

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        files: "backend/.*\\.py$"

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        files: "backend/.*\\.py$"
        args: [--config=backend/.flake8]

# JavaScript/Svelte hooks
-   repo: local
    hooks:
    -   id: eslint
        name: eslint
        entry: bash -c 'cd frontend/web && npx eslint --no-error-on-unmatched-pattern'
        language: system
        files: "frontend/web/.*\\.js$"
        pass_filenames: true

    -   id: prettier
        name: prettier
        entry: bash -c 'cd frontend/web && npx prettier --config .prettierrc --write "**/*.js" "**/*.json" && git add .'
        language: system
        files: "frontend/web/.*\\.(js|json)$"
        pass_filenames: false
