version: '3.8'

services:
  # PostgreSQL database
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=vacationplanner
      - POSTGRES_USER=vacplan
      - POSTGRES_DB=vacation_planner
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vacplan -d vacation_planner"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend FastAPI service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_ENV=production
      - DB_USER=vacplan
      - DB_PASSWORD=vacationplanner
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=vacation_planner
    command: >
      sh -c "python initialize_db.py && 
             python add_sample_holidays.py && 
             uvicorn app.main:app --host 0.0.0.0 --port 8000"

  # Frontend SvelteKit service
  frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000/api

volumes:
  postgres_data: 