name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run tests
      run: |
        cd backend
        pytest --cov=app

  lint-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort

    - name: Lint Python code
      run: |
        cd backend
        flake8 --config=.flake8 .
        black --check .
        isort --check .

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd frontend/web
        npm ci
        # Install specific ESLint version compatible with .eslintrc.js
        npm install eslint@8.56.0 --save-dev

    - name: Lint JavaScript/Svelte code
      run: |
        cd frontend/web
        npx eslint --config .eslintrc.js .
        npx prettier --config .prettierrc --check .

    - name: Build frontend
      run: |
        cd frontend/web
        npm run build
